defaults: &defaults
  notification_rest_service_url: http://localhost:8080/notify

development:
  <<: *defaults

dev:
  <<: *defaults
  notification_rest_service_url: http://flash-dev-java1:8080/notify

test:
  <<: *defaults
  notification_rest_service_url: http://flash-test-java1:8080/notify

preprod:
  <<: *defaults
  notification_rest_service_url: http://flash-preprod-java1:8080/notify

production:
  <<: *defaults
  notification_rest_service_url: http://flash-prod-java1:8080/notify