defaults: &defaults
  notification_rest_service_url: http://localhost:8080/notify

development:
  <<: *defaults

dev:
  <<: *defaults
  notification_rest_service_url: http://flash-dev-java1:8080/notify

test:
  <<: *defaults

preprod:
  <<: *defaults

production:
  <<: *defaults